# Generated by Django 6.0 on 2025-12-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PowderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPowderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProteinOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonInfo',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proteinSearch.product')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('available_on_amazon', models.BooleanField()),
                ('amazon_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('amazon_review_count', models.IntegerField()),
                ('amazon_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proteinSearch.product')),
                ('additives_and_sweeteners', models.TextField()),
                ('gluten_free', models.BooleanField()),
                ('third_party_tested', models.BooleanField()),
                ('scoop_included', models.BooleanField()),
                ('lactose_free', models.BooleanField()),
                ('flavor_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proteinSearch.product')),
                ('calories_per_scoop', models.IntegerField()),
                ('protein_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bcaas_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar_free', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServingInfo',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proteinSearch.product')),
                ('servings_per_container', models.IntegerField()),
                ('price_per_serving', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_count_oz', models.DecimalField(decimal_places=1, max_digits=5)),
                ('item_weight_lbs', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'model'), name='unique_product'),
        ),
        migrations.AddField(
            model_name='productpowdertype',
            name='powder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinSearch.powdertype'),
        ),
        migrations.AddField(
            model_name='productpowdertype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinSearch.product'),
        ),
        migrations.AddField(
            model_name='productproteinorigin',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinSearch.product'),
        ),
        migrations.AddField(
            model_name='productproteinorigin',
            name='protein_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinSearch.proteinorigin'),
        ),
        migrations.AddConstraint(
            model_name='productpowdertype',
            constraint=models.UniqueConstraint(fields=('product', 'powder_type'), name='unique_product_powdertype'),
        ),
        migrations.AddConstraint(
            model_name='productproteinorigin',
            constraint=models.UniqueConstraint(fields=('product', 'protein_origin'), name='unique_product_proteinorigin'),
        ),
    ]
