# Generated by Django 6.0 on 2025-12-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteinSearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazoninfo',
            name='amazon_link',
        ),
    ]
