# Generated by Django 6.0 on 2025-12-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinSearch', '0002_remove_amazoninfo_amazon_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='additives_and_sweeteners',
            field=models.BooleanField(),
        ),
    ]
