# Generated by Django 6.0 on 2025-12-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinSearch', '0004_userreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazoninfo',
            name='amazon_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='amazoninfo',
            name='amazon_review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazoninfo',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='bcaas_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='calories_per_scoop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='carbs_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='fat_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='protein_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servinginfo',
            name='item_weight_lbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='servinginfo',
            name='price_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='servinginfo',
            name='servings_per_container',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servinginfo',
            name='unit_count_oz',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='review_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
