# Generated by Django 6.0 on 2025-12-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinSearch', '0005_alter_amazoninfo_amazon_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazoninfo',
            name='amazon_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='amazoninfo',
            name='amazon_review_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
